name: dart_dice_parser
description: A dart library for parsing dice notation (`2d6+4`). Supports advantage/disadvantage, exploding die, and other variations.
version: 8.0.0
homepage: https://github.com/Adventuresmith/dart-dice-parser
repository: https://github.com/Adventuresmith/dart-dice-parser

environment:
  sdk: "^3.8.0"

topics:
  - dice
  - rpg
  - ttrpg

dependencies:
  collection: ^1.0.0
  equatable: ^2.0.0
  fast_immutable_collections: ^11.0.0
  logging: ^1.3.0
  # TODO: upgrade to 7.0.0 once version constraints from stable flutter sdk don't barf
  petitparser: ^6.1.0

dev_dependencies:
  io: ^1.0.0
  lint: ^2.8.0
  mocktail: ^1.0.0
  test: ^1.0.0
